### PR TITLE
RFC: adding scaled (or something better?)

### PR DESCRIPTION
**Pull request by joshday**
I'll be removing tuning parameters from penalties (see https://github.com/JuliaML/PenaltyFunctions.jl/issues/10), but adding in scaled versions, similar to @Evizero's scaled loss types.  It'd be nice if Losses and Penalties could share a function which returns a scaled version.

### CODE REVIEW

**Comment by Evizero** [comment]
I am guessing you don't really plan on making to scale factor a type parameter? What do you think about just overloading `*(::Number, ::Penalty)` ?

**Comment by joshday** [comment]
I actually have included the scale factor as a type parameter.   I've borrowed most of what you've done with scaled loss:

```julia
immutable ScaledElementPenalty{P <: ElementPenalty, λ} <: ElementPenalty
    penalty::P
    ScaledElementPenalty(pen::P) = typeof(λ) <: Number ? new(pen) : _scaled_error()
end
```

`@code_llvm` just looks sooo nice
```julia
julia> @code_llvm deriv(PenaltyFunctions.scaled(L2Penalty(), .1), rand())

define double @julia_deriv_72016(double) #0 {
top:
  %1 = fmul double %0, 1.000000e-01
  ret double %1
}
```

**Comment by joshday** [comment]
> What do you think about just overloading *(::Number, ::Penalty) ?

I'm not entirely opposed, but it would be a pretty nontraditional overload.  I think I like the look of `scaled` better.

```julia
s = .1 * L1Penalty()

s = scaled(L1Penalty(), .1)
```

**Comment by Evizero** [comment]
Well, but if you don't make use `Val{0.1}` anyway, it would be more readable and julian to to write `0.1 * L2Penalty()` instead of `PenaltyFunctions.scaled(L2Penalty(), .1)`.

I guess my current thought is that maybe a binary function named `scaled` seems a bit obsolete if the signature for `*` is also available. This probably also applies to LossFunctions.

The remaining problem of using a float value directly is that promoting it to a type parameter has overhead and messes with type-inference of the scope.

**Comment by Evizero** [comment]
Mhm, well it is also growing on me the more I think about it. especially considering that we should encourage `scaled(L2Penalty, Val{0.1})`

**Comment by joshday** [comment]
Well scaled does this.  Is there any situation this wouldn't be preferred?
```julia
scaled(p::ElementPenalty, λ::Number) = ScaledElementPenalty(p, Val{λ})
```

**Comment by Evizero** [comment]
> Well scaled does this. Is there any situation this wouldn't be preferred?

Does the issue described in https://github.com/joshday/SparseRegression.jl/issues/5 not occur for you? maybe the way you specify it the compiler figures out that you are using a constant that is known at compile time? Unsure

**Comment by joshday** [comment]
Maybe?  I would need to look more into that.  I've also included additional methods for scaling an unscaled penalty, which would probably be the recommended usage for factors decided at run time.

```julia
value(L1Penalty(), x, .1) == value(scaled(L1Penalty(), .1), x)
deriv(L1Penalty(), x, .1) == deriv(scaled(L1Penalty(), .1), x)
 prox(L1Penalty(), x, .1) ==  prox(scaled(L1Penalty(), .1), x)
```

**Comment by Evizero** [comment]
certainly worth investigating I think. I do like the idea of a similar interface philosophy for losses and penalties

**Comment by Evizero** [comment]
The question that remains for this particular PR is, should we export the function?

**Comment by joshday** [comment]
I'm up for it if you are.

**Comment by Evizero** [comment]
I re-triggered the tests and will merge once done (they should work now that #20 was fixed). I'll then export the function and tag a new version

**Pull request merged**
