### PR TITLE
Introduce StatsBase dependency; add tests; add docstrings

### PR DESCRIPTION
**Pull request by Evizero**

### CODE REVIEW

**Comment by Evizero** [comment]
Do we want to remove `abstract Optimizer` for now until we see how the `Optim.jl` changes turn out?

**Comment by Evizero** [comment]
cc: @ahwillia

**Comment by ahwillia** [comment]
+1 for removing `Optimizer` temporarily. I'm pretty sure I'm supposed to be the one contributing optimization code under the JuliaML umbrella but I've been spread too thin. Also, Optim is starting to look really promising.

This looks good to merge to me. Unless you think others might want to weigh in first.

**Comment by Evizero** [comment]
I shall remove the optimizer then. Seems a hard sell for METADATA right now anyway

**Comment by tbreloff** [comment]
Yes fine to remove. Hopefully someday Optim can depend on LearnBase and we
can add it back.  I think StochasticOptimization should be on hold until we
decide Optim doesn't fulfill what we need. Of course we should contribute
to Optim if it's just missing functionality, as opposed to philosophical
differences.

**Comment by ahwillia** [comment]
Stochastic Optimization will end up needing a slightly different API, so
will have to be a separate package, but agree nonetheless Tom.

**Pull request merged**
