### PR TITLE
remove ObsDims and data iterators

### PR DESCRIPTION
**Pull request by CarloLucibello**
Continuation of #44 
(I'm a bit lazy to figure out how to push into another person PR right now so I'm opening this new PR)

Compared to #44, this 
- doesn't add the label-related functions
- fixes tests,
- improves some docs
- removes a few abstract classes for data iteration that I think we can well live without

### CODE REVIEW

**Comment by darsnack** [comment]
Thanks for taking this up. #44 is done; the only remaining blocker is https://github.com/JuliaML/MLDataPattern.jl/pull/50. MLLabelUtils.jl PR (https://github.com/JuliaML/MLLabelUtils.jl/pull/44) is also done.

Label-related functions were added cause that's what the comments for MLLabelUtils.jl indicated needed to be done. I'll give you write access to all my forks if you want to push the 3 PRs forward.

**Comment by CarloLucibello** [comment]
I'm merging this as it is, since downstream packages updates should not be considered blockers, they will be ready to update their compat bounds when they will be ready. 

Also, I'd like to leverage `getobs` and `nobs` as soon as possible to finally have a consistent dataset interface across the ecosystem.

**Comment by darsnack** [comment]
I don't think everything here should have been merged. The state of #44 was necessary for the downstream PRs.

**Comment by darsnack** [comment]
The deleted types are also break MLDataPattern.jl. Can you revert this commit and just apply the version bump + test fix?

I agree with getting rid of types we don't need in the long term, but right now I am trying to update MLDataPattern.jl and MLLabelUtils.jl for the new interface. Too many clean up changes make refactoring the codebase too uncertain.

**Comment by CarloLucibello** [comment]
ok

**Comment by darsnack** [comment]
Thanks

**Comment by johnnychen94** [comment]
My main focus is still on JuliaImages so sorry that I don't have more spare time to help here.

**Pull request merged**
