### PR TITLE
syntax changes for 0.6

### PR DESCRIPTION
**Pull request by joshday**
Now that 0.6 is on feature freeze, this fixes deprecation warnings on 0.6.  There's no hurry yet, but it would be great when the time comes if we had PRs ready for the packages depending on LearnBase so we could all flip the switch at the same time.

### CODE REVIEW

**Comment by Evizero** [comment]
nice. thanks! Yea let's wait a little bit with merging this

**Comment by Evizero** [comment]
Let's maybe go the `Compat` route at first? 

e.g. add `Compat 0.17` into the `REQUIRE` file and write

```julia
@compat abstract type ValueHistory end
```

this way we can support 0.5 and 0.6 for a little while

**Comment by joshday** [comment]
I view supporting 0.5 as not entirely worth it.  It slows down development time and I envision JuliaML users adopting 0.6 quickly.  That being said, I'm okay with going the compat route in the short term.

**Comment by Evizero** [comment]
fair enough. well it will make the transition easier I think.

**Comment by Evizero** [comment]
I'll make a commit on this PR

**Comment by Evizero** [comment]
once the tests pass on 0.5 and 0.6 (which locally they do) I'd be ok merging this and tagging `v0.1.3`

**Comment by tbreloff** [comment]
I think in general it's easiest to tag a final 0.5 release (if needed) then
increment the minor version and move to 0.6 minimum. If necessary you can
always backport critical changes and bump the older tag for 0.5 updates.

**Comment by Evizero** [comment]
That is the plan. but there are multiple packages to get ready, and I would like a smooth and simple way to do it. The sub-packages of LearnBase already have a minor and major version limit in order to coordinate upstream moves (i.e. moving code from a subpackage here) smoothly without breaking things, so I'd like to keep the effort needed to upgrade manageable for me.

Once 0.6 is out for a bit I'll remove compat again

**Pull request merged**
