### PR TITLE
move targets, gettargets, and gettarget here from MLDataUtils

### PR DESCRIPTION
**Pull request by Evizero**

### CODE REVIEW

**Comment by joshday** [comment]
I was looking through LearnBase yesterday and wondering if we should move the docstrings to where the methods are defined.

For example, I don't like that this happens, because I also don't know how to find the definition that this docstring says exists:
```julia
julia> using LearnBase

help?> getobs
search: getobs getobs! get_zero_subnormals

  getobs(data, [idx], [obsdim])

  Returns the observations corresponding to the observation-index idx. Note that idx can be of type Int or
  AbstractVector.

  If it makes sense for the type of data, obsdim can be used to specify which dimension of data denotes the
  observations. It can be specified in a typestable manner as a positional argument (see ?ObsDim), or more
  conveniently as a smart keyword argument.

julia> getobs(randn(100, 10), 1, ObsDim.First())
ERROR: MethodError: no method matching getobs(::Array{Float64,2}, ::Int64, ::LearnBase.ObsDim.Constant{1})
```

**Comment by Evizero** [comment]
That is a good point. The main idea behind having the docstring here is that they kinda define the basic interface of that function. But I guess we could do that as comments instead?

**Comment by Evizero** [comment]
Point being that LearnBase should in a way dictate how the signature of that function should look like

**Comment by joshday** [comment]
> LearnBase should in a way dictate how the signature of that function should look like

Agreed.  I think some small changes to the current docs would be sufficient.  Something like

- `LearnBase` specification: `getobs(data, [idx], [obsdim])`, or
- New methods should implement `getobs(data::TypeOfData, [idx], [obsdim])`

**Comment by Evizero** [comment]
Ok. I'll remove the docstring back before merging this PR. I'll also move the `getobs` ones.

**Comment by Evizero** [comment]
something like this?

**Comment by joshday** [comment]
By including where they are implemented, I would be okay with leaving those as docstrings, but that's up to you.

**Comment by Evizero** [comment]
I think this is in general better, since the doc strings are intended for end-users, while we can write the comments in a way that is just targeted at developers.

**Pull request merged**
